apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: maukas/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
        '**/*.css': .
        '**/*.html': .
    - image: maukas/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
    - image: maukas/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '**/*.js': .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
      - k8s/server-deployment.yaml
      - k8s/worker-deployment.yaml
      - k8s/client-cluster-ip-service.yaml
      - k8s/server-cluster-ip-service.yaml
      - k8s/database-persistent-volume-claim.yaml
      - k8s/ingress-service.yaml
      - k8s/postgres-cluster-ip-service.yaml
      - k8s/postgres-deployment.yaml
      - k8s/redis-cluster-ip-service.yaml
      - k8s/redis-deployment.yaml